alias:
  name: Cashbox_Auto_Replenish_Settings
  system: amplitude
clickhouse:
  enabled: true
meta:
  description: Необходимо добавить описание события
  labels:
  - sme_transfer_script
  maintainers: []
  tasks: []
parameters:
  count_accounts:
    alias: count_accounts
    meta:
      description: Необходимо добавить описание параметра
    nullable: false
    type: String
  count_change:
    alias: count_change
    meta:
      description: Необходимо добавить описание параметра
    nullable: false
    type: String
  percent:
    alias: percent
    meta:
      description: Необходимо добавить описание параметра
    nullable: false
    type: String
settings: {}
