alias:
  name: Origination_Application_Main_Shown
  system: amplitude
clickhouse:
  enabled: true
meta:
  description: При успешной загрузке экрана статуса заявки
  labels:
  - sme_transfer_script
  maintainers: []
  tasks: []
parameters:
  applStatus:
    alias: applStatus
    meta:
      description: Необходимо добавить описание параметра
    nullable: false
    type: String
  id:
    alias: id
    meta:
      description: Необходимо добавить описание параметра
    nullable: false
    type: String
settings: {}
