alias:
  name: Application_Shown
  system: amplitude
clickhouse:
  enabled: true
meta:
  description: показали форму заявки на открытие счета
  labels:
  - sme_transfer_script
  maintainers: []
  tasks: []
parameters: {}
settings: {}
