alias:
  name: Overnight_Auto_Replenish_Settings
  system: amplitude
clickhouse:
  enabled: true
meta:
  description: Необходимо добавить описание события
  labels:
  - sme_transfer_script
  maintainers: []
  tasks: []
parameters:
  all_money:
    alias: all_money
    meta:
      description: Необходимо добавить описание параметра
    nullable: false
    type: String
  inviolable_money:
    alias: inviolable_money
    meta:
      description: Необходимо добавить описание параметра
    nullable: false
    type: String
settings: {}
